### ISSUE TITLE
Configure Samba smb.conf attributes for use with Final Cut Pro

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/arm-nas#9]
There are many `fruit` options for SMB that should help with macOS compatibility: https://www.mankier.com/8/vfs_fruit

Right now, when I try opening a Final Cut Pro project direct from the disk array, it errors out saying it needs different storage: 

<img width="752" alt="Screenshot 2024-04-03 at 3 30 12 PM" src="https://github.com/geerlingguy/hl15-arm64-nas/assets/481677/9e54f6db-25f1-4ab3-8582-322141f0631a">

"Unsupported volume type - Choose a local, SAN, or supported SMB location."

**Comment by tomasdev** [comment]
For anyone coming here from Google... the option that ads `catia` to the vfs object is the checkbox named "Use Apple-style Character Encoding" on your SMB Share Advanced Options.

**Comment by geerlingguy** [comment]
@tomasdev - indeed, looks like that's a TrueNAS feature? Part of the [SMB Share Screen](https://www.truenas.com/docs/core/uireference/sharing/smbsharescreen/)
